import process from 'process';
import esbuild from 'esbuild';
import builtins from 'builtin-modules';
import copyFilePlugin from 'esbuild-plugin-copy-file';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    bundle: true,
    entryPoints: ['main.ts'],
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    logLevel: 'info',
    minify: prod,
    outfile: 'dist/main.js',
    plugins: [
        copyFilePlugin({
            before: {
                // copy before bundling
            },
            after: {
                // copy after bundling
                // './docs/CHANGELOG.md': './CHANGELOG.md',
                './dist/manifest.json': './manifest.json',
            },
        }),
    ],
    sourcemap: prod ? false : 'inline',
    target: 'es2018',
    treeShaking: true,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
